os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
env:
  CXX: "g++-6"
  CC: "gcc-6"
install:
  - pip install conan
  - conan user
script:
  - conan install .
  - cmake . -G "Unix Makefiles"
  - cmake --build .
  - ctest